/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.math.BigInteger;
import java.security.MessageDigest;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;


/**
 *
 *
 */
public class FrmRegister extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public FrmRegister() {
        initComponents();
        this.setLocationRelativeTo(null);
        // create a button group for the radiobuttons
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButton_hombre);
        bg.add(jRadioButton_mujer);

        Border text_inicio_sesion = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);
        jText_inicio_sesion.setBorder(text_inicio_sesion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jRadioButton_mujer = new javax.swing.JRadioButton();
        jRadioButton_hombre = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jBtn_registrar = new javax.swing.JButton();
        jTextField_nombre_completo = new javax.swing.JTextField();
        jTextField_nombre_usuario = new javax.swing.JTextField();
        jTextField_num_doc1 = new javax.swing.JTextField();
        jTextField_num_tel2 = new javax.swing.JTextField();
        jTextField_correo1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField_confirm = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jText_inicio_sesion = new javax.swing.JTextField();

        jRadioButton3.setText("jRadioButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(null);

        jPanel4.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel12.setText("Registro");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(150, 10, 107, 55);

        jLabel13.setText("Nombre Completo:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(30, 90, 120, 16);

        jLabel14.setText("Nombre de Usuario:");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(30, 130, 120, 16);

        jLabel15.setText("Contraseña:");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(80, 350, 100, 16);

        jLabel16.setText("Confirma la contraseña:");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(10, 390, 160, 16);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cédula de Ciudadanía", "Cédula de extranjería" }));
        jPanel4.add(jComboBox3);
        jComboBox3.setBounds(170, 160, 152, 22);

        jLabel17.setText("Tipo de documento:");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(30, 160, 150, 16);

        jLabel18.setText("Correo electrónico:");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(40, 320, 140, 16);

        jLabel19.setText("Numero de documento:");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(10, 200, 160, 20);

        jLabel20.setText("Genero:");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(100, 240, 80, 16);

        jRadioButton_mujer.setText("Mujer");
        jPanel4.add(jRadioButton_mujer);
        jRadioButton_mujer.setBounds(170, 240, 54, 20);

        jRadioButton_hombre.setText("Hombre");
        jPanel4.add(jRadioButton_hombre);
        jRadioButton_hombre.setBounds(250, 240, 67, 20);

        jLabel21.setText("Numero telefonico:");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(40, 280, 130, 16);

        jBtn_registrar.setBackground(new java.awt.Color(153, 153, 153));
        jBtn_registrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtn_registrar.setForeground(new java.awt.Color(0, 0, 0));
        jBtn_registrar.setText("Registrar");
        jBtn_registrar.setBorderPainted(false);
        jBtn_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtn_registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtn_registrarMouseExited(evt);
            }
        });
        jBtn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_registrarActionPerformed(evt);
            }
        });
        jPanel4.add(jBtn_registrar);
        jBtn_registrar.setBounds(130, 460, 140, 38);

        jTextField_nombre_completo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(153, 153, 153), null, null));
        jPanel4.add(jTextField_nombre_completo);
        jTextField_nombre_completo.setBounds(170, 90, 150, 22);

        jTextField_nombre_usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(153, 153, 153), null, null));
        jPanel4.add(jTextField_nombre_usuario);
        jTextField_nombre_usuario.setBounds(170, 130, 150, 22);

        jTextField_num_doc1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(153, 153, 153), null, null));
        jPanel4.add(jTextField_num_doc1);
        jTextField_num_doc1.setBounds(170, 200, 150, 22);

        jTextField_num_tel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(153, 153, 153), null, null));
        jPanel4.add(jTextField_num_tel2);
        jTextField_num_tel2.setBounds(170, 280, 150, 22);

        jTextField_correo1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(153, 153, 153), null, null));
        jPanel4.add(jTextField_correo1);
        jTextField_correo1.setBounds(170, 320, 150, 22);

        jPasswordField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(153, 153, 153), null, null));
        jPanel4.add(jPasswordField1);
        jPasswordField1.setBounds(170, 350, 150, 22);

        jPasswordField_confirm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(153, 153, 153), null, null));
        jPanel4.add(jPasswordField_confirm);
        jPasswordField_confirm.setBounds(170, 390, 150, 22);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 390, 570);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        jText_inicio_sesion.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jText_inicio_sesion.setText("¿Ya tienes cuenta? Inicia sesión");
        jText_inicio_sesion.setBorder(null);
        jText_inicio_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jText_inicio_sesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel22))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jText_inicio_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel22)
                .addGap(63, 63, 63)
                .addComponent(jText_inicio_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(390, 0, 420, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText_inicio_sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jText_inicio_sesionMouseClicked
        // TODO add your handling code here:
        // Cerrar el JFrame actual
        dispose();

        // Abrir el JFrame de inicio sesion
        vista.Login rf = new vista.Login();
        rf.setVisible(true);
        rf.pack();
        rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();


    }//GEN-LAST:event_jText_inicio_sesionMouseClicked

    private void jBtn_registrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_registrarMouseEntered
        // TODO add your handling code here:
        // set jbutton background
        jBtn_registrar.setBackground(new Color(225, 20, 2));
    }//GEN-LAST:event_jBtn_registrarMouseEntered

    private void jBtn_registrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_registrarMouseExited
        // TODO add your handling code here:
        // set jbutton background
        jBtn_registrar.setBackground(new Color(235, 47, 6));
    }//GEN-LAST:event_jBtn_registrarMouseExited

    private void jBtn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_registrarActionPerformed
        // TODO add your handling code here:
         // Obtener los datos de los campos
    String nombreCompleto = jTextField_nombre_completo.getText();
    String nombreUsuario = jTextField_nombre_usuario.getText();
    String tipoId = (String) jComboBox3.getSelectedItem();
    String numeroDocumento = jTextField_num_doc1.getText();
    String telefono = jTextField_num_tel2.getText();
    String correo = jTextField_correo1.getText();
    String contraseña = String.valueOf(jPasswordField1.getPassword());
    String pass2 = String.valueOf(jPasswordField_confirm.getPassword());
    String genero = "Hombre";

    // Validar los campos
    if (verifyFields()) {
        // Validar que las contraseñas coincidan
        if (!contraseña.equals(pass2)) {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return; // Salir si las contraseñas no coinciden
        }

        // Encriptar la contraseña utilizando SHA-1
        String sha1 = "";
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-1");
            digest.reset();
            digest.update(contraseña.getBytes("utf8"));
            sha1 = String.format("%040x", new BigInteger(1, digest.digest()));
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al encriptar la contraseña", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si ocurre un error
        }

        // Verificar el género
        if (jRadioButton_mujer.isSelected()) {
            genero = "Mujer";
        }
        
        modelo.Usuarios usuarios;
        // Crear un objeto de usuario
        usuarios = new modelo.Usuarios(1, nombreCompleto, nombreUsuario, tipoId, numeroDocumento, genero, telefono, correo, sha1);

        // Intentar insertar el usuario en la base de datos
        try {
            modelo.Usuarios.insertUser(usuarios);
            JOptionPane.showMessageDialog(null, "Registrado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            mostrarLogin(); // Redirigir a la ventana de inicio de sesión
        } catch (Exception e) {
            e.printStackTrace(); // Imprimir detalles del error
            JOptionPane.showMessageDialog(null, "Error al registrar el usuario: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }

    }

// Método para mostrar la ventana de inicio de sesión
    private void mostrarLogin() {
        this.dispose(); // Cierra la ventana actual
        Login login = new Login(); 
        login.setVisible(true);
    }

    // Método de validación de campos
    /*private boolean verifyFields() {
    }//GEN-LAST:event_jBtn_registrarActionPerformed
*/
    // create a function to verify the empty fields  
     public boolean verifyFields() {
        String name = jTextField_nombre_completo.getText();
        String username = jTextField_nombre_usuario.getText();
        String tipoId = (String) jComboBox3.getSelectedItem();
        String id = jTextField_num_doc1.getText();
        String genero = "Hombre";
        String telefono = jTextField_num_tel2.getText();
        String email = jTextField_correo1.getText();
        String pass = String.valueOf(jPasswordField1.getPassword());
        String passconf = String.valueOf(jPasswordField_confirm.getPassword());

        // Verificar si hay campos vacíos
        if (name.trim().equals("") || username.trim().equals("") || tipoId == null || tipoId.trim().equals("")
                || id.trim().equals("") || telefono.trim().equals("") || email.trim().equals("")
                || pass.trim().equals("") || passconf.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Uno o más campos están vacíos", "Campos vacíos", 2);
            return false;
        } // Verificar si las contraseñas coinciden
        else if (!pass.equals(passconf)) {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "Confirmar contraseña", 2);
            return false;
        } // Si todo está bien
        else {
            return true;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtn_registrar;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField_confirm;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton_hombre;
    private javax.swing.JRadioButton jRadioButton_mujer;
    private javax.swing.JTextField jTextField_correo1;
    private javax.swing.JTextField jTextField_nombre_completo;
    private javax.swing.JTextField jTextField_nombre_usuario;
    private javax.swing.JTextField jTextField_num_doc1;
    private javax.swing.JTextField jTextField_num_tel2;
    private javax.swing.JTextField jText_inicio_sesion;
    // End of variables declaration//GEN-END:variables
}
