/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Dimension;
import java.math.BigInteger;
import java.security.MessageDigest;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JPasswordField;
import javax.swing.border.Border;

/**
 *
 * @author piper
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {

        initComponents();

        this.setLocationRelativeTo(null);

        Border label_registro_cuenta = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);
        jLabel_registro.setBorder(label_registro_cuenta);

        Border label_border = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        jLabel_minimizar.setBorder(label_border);
        jLabel_cerrar.setBorder(label_border);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1_usuario = new javax.swing.JLabel();
        jLabel_contraseña = new javax.swing.JLabel();
        jbtnAcceso1 = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jLabel_registro = new javax.swing.JLabel();
        jText_usuario = new javax.swing.JTextField();
        jLabel_minimizar = new javax.swing.JLabel();
        jLabel_cerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(112, 145, 255));
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setEnabled(false);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel9.setText("Acceso");

        jLabel1_usuario.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel1_usuario.setText("Usuario*");

        jLabel_contraseña.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel_contraseña.setText("Contraseña*");

        jbtnAcceso1.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jbtnAcceso1.setText("Iniciar sesión");
        jbtnAcceso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAcceso1ActionPerformed(evt);
            }
        });

        jPassword.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFocusLost(evt);
            }
        });
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        jLabel_registro.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel_registro.setText("¿Aún no tienes cuenta? Regístrate");
        jLabel_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_registroMouseClicked(evt);
            }
        });

        jText_usuario.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jText_usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jText_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jText_usuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jText_usuarioFocusLost(evt);
            }
        });
        jText_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_usuarioActionPerformed(evt);
            }
        });

        jLabel_minimizar.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel_minimizar.setText("  - ");
        jLabel_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_minimizar.setPreferredSize(new java.awt.Dimension(18, 22));
        jLabel_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizarMouseExited(evt);
            }
        });

        jLabel_cerrar.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel_cerrar.setText("  X");
        jLabel_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_cerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(378, 378, 378)
                        .addComponent(jLabel_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1_usuario))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel_contraseña))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jbtnAcceso1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel_registro))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1_usuario)
                        .addGap(6, 6, 6)
                        .addComponent(jText_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel_contraseña)
                        .addGap(18, 18, 18)
                        .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jbtnAcceso1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_cerrar)
                        .addComponent(jLabel_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(jLabel_registro)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jbtnAcceso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAcceso1ActionPerformed
        // TODO add your handling code here:
        // Componentes de la interfaz (campos y botones)
        PreparedStatement st = null;
        ResultSet rs = null;

        // Obtener datos de los campos
        String nombre_usuario = jText_usuario.getText().trim();
        String contraseña = String.valueOf(jPassword.getPassword());

        // ===== VALIDACIONES ANTES DE ENCRIPTAR =====
        // Validar que no estén vacíos o con el placeholder
        if (nombre_usuario.isEmpty() || nombre_usuario.equalsIgnoreCase("Nombre de Usuario")) {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa tu nombre de usuario", "Usuario vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (contraseña.isEmpty() || contraseña.equalsIgnoreCase("Contraseña")) {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa tu contraseña", "Contraseña vacía", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ENCRIPTAR LA CONTRASEÑA CON SHA-1 
        String sha1 = "";
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-1");
            digest.reset();
            digest.update(contraseña.getBytes("utf8"));
            sha1 = String.format("%040x", new BigInteger(1, digest.digest()));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al procesar la contraseña: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //  CONSULTAR EN LA BASE DE DATOS 
        try {
            //Obtener TODOS los datos necesarios
            String query = "SELECT `id`, `nombre_completo`, `nombre_usuario`, `contraseña`, `rol` "
                    + "FROM `usuarios` "
                    + "WHERE `nombre_usuario` = ? AND `contraseña` = ?";

            st = modelo.Conexion_DB.getConnection().prepareStatement(query);
            st.setString(1, nombre_usuario);
            st.setString(2, sha1);

            System.out.println("Ejecutando query de autenticación...");

            rs = st.executeQuery();

            if (rs.next()) {
                //  LOGIN EXITOSO
                System.out.println("✅ Usuario encontrado en la base de datos");

                // Obtener todos los datos del usuario
                int idUsuario = rs.getInt("id");
                String nombreCompleto = rs.getString("nombre_completo");
                String usuarioDB = rs.getString("nombre_usuario");
                String rolUsuario = rs.getString("rol");

                System.out.println("ID: " + idUsuario);
                System.out.println("Nombre: " + nombreCompleto);
                System.out.println("Rol: " + rolUsuario);

                //  INICIAR SESIÓN EN EL SISTEMA
                modelo.Usuario_Sesion.getInstancia().iniciarSesion(
                        idUsuario,
                        nombreCompleto,
                        usuarioDB,
                        rolUsuario
                );

                //  ABRIR VENTANA PRINCIPAL
                HmPrincipal form = new HmPrincipal();
                form.pack();
                form.setExtendedState(JFrame.MAXIMIZED_BOTH);
                form.setVisible(true);
                form.setLocationRelativeTo(null);
                form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

                // Cerrar ventana de login
                this.dispose();

            } else {
                //  LOGIN FALLIDO
                System.out.println("❌ No se encontró el usuario con esas credenciales");
                JOptionPane.showMessageDialog(null,
                        "Usuario o contraseña incorrectos",
                        "Error de autenticación",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            System.out.println("❌ Error SQL: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,
                    "Error de conexión a la base de datos:\n" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            // CERRAR RECURSOS
            try {
                if (rs != null) {
                    rs.close();
                }
                if (st != null) {
                    st.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jbtnAcceso1ActionPerformed

    private void jLabel_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_registroMouseClicked
        // TODO add your handling code here:
        // Cerrar el JFrame actual
        dispose();

        // Abrir el JFrame de registro
        FrmRegister registro = new FrmRegister();
        registro.setVisible(true);
    }//GEN-LAST:event_jLabel_registroMouseClicked

    private void jLabel_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizarMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_cerrar.setBorder(label_border);
        jLabel_cerrar.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_minimizarMouseClicked

    private void jLabel_minimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizarMouseEntered
        // TODO add your handling code here:

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_minimizar.setBorder(label_border);
        jLabel_minimizar.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_minimizarMouseEntered

    private void jLabel_minimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizarMouseExited
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_minimizar.setBorder(label_border);
        jLabel_minimizar.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_minimizarMouseExited

    private void jLabel_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_cerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel_cerrarMouseClicked

    private void jLabel_cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_cerrarMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_cerrar.setBorder(label_border);
        jLabel_cerrar.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_cerrarMouseEntered

    private void jLabel_cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_cerrarMouseExited
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_cerrar.setBorder(label_border);
        jLabel_cerrar.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_cerrarMouseExited

    private void jText_usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jText_usuarioFocusGained
        // TODO add your handling code here:
        // Limpiar el campo de texto al enfocar si el texto es "usuario"
        if (jText_usuario.getText().trim().toLowerCase().equals("Nombre de Usuario")) {
            jText_usuario.setText("");  // Limpiar el campo de texto
            jText_usuario.setForeground(Color.black);  // Cambiar el color del texto a negro
        }

    }//GEN-LAST:event_jText_usuarioFocusGained

    private void jText_usuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jText_usuarioFocusLost
        // TODO add your handling code here:
        if (jText_usuario.getText().trim().equals("")
                || jText_usuario.getText().trim().toLowerCase().equals("Nombre de Usuario")) {
            jText_usuario.setText("Nombre de Usuario");  // Establecer el texto "Usuario" en el campo de texto
            jText_usuario.setForeground(new Color(153, 153, 153));  // Cambiar el color del texto a gris claro
        }

    }//GEN-LAST:event_jText_usuarioFocusLost

    private void jPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusGained
        // TODO add your handling code here:

        // Obtener el texto de la contraseña
        String pass = String.valueOf(jPassword.getPassword());

        if (pass.trim().toLowerCase().equals("Contraseña")) {
            jPassword.setText("");  // Limpiar el campo de contraseña
            jPassword.setForeground(Color.black);  // Cambiar el color del texto a negro
        }
    }//GEN-LAST:event_jPasswordFocusGained

    private void jPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusLost
        // TODO add your handling code here:
        // Convertir la contraseña ingresada en el campo de contraseña a un String
        String pass = String.valueOf(jPassword.getPassword());

        if (pass.trim().equals("")
                || pass.trim().toLowerCase().equals("Contraseña")) {
            jPassword.setText("Contraseña");  // Establecer el texto "contraseña" en el campo de contraseña
            jPassword.setForeground(new Color(153, 153, 153));  // Cambiar el color del texto a gris claro
        }
    }//GEN-LAST:event_jPasswordFocusLost

    private void jText_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel1_usuario;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_cerrar;
    private javax.swing.JLabel jLabel_contraseña;
    private javax.swing.JLabel jLabel_minimizar;
    private javax.swing.JLabel jLabel_registro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jText_usuario;
    private javax.swing.JButton jbtnAcceso1;
    // End of variables declaration//GEN-END:variables
}
